# Site settings
title: Hugo “Kitty” Giraudel
description: >
  I’m Hugo “Kitty” Giraudel, a non-binary web developer based in Berlin, focused on accessibility and inclusivity.
url: "https://hugogiraudel.com"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Pagination settings
plugins: [jekyll-paginate]
paginate_path: /blog/:num
paginate: 10

# Posts settings
permalink: pretty
future: false
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"

# Sass settings
sass:
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - LICENSE
  - node_modules
  - workbox-config.js
include:
  - _redirects
environment: production

# Navigation
nav:
  - label: Writing
    url: /blog/
  - label: Coding
    url: /projects/
  - label: Speaking
    url: /speaking/
  - label: About
    url: /about/

# Liquid utilities
empty_list: []

collections:
  recipes:
    output: true
