# Site settings
title: Hugo Giraudel, front-end developer in Berlin
email: hugo.giraudel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Hugo Giraudel, I am a French front-end developer based in Berlin, focused on accessibility and inclusivity.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hugogiraudel.com" # the base hostname & protocol for your site
twitter_username: HugoGiraudel
github_username:  HugoGiraudel

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Pagination settings
gems: [jekyll-paginate]
paginate_path: /blog/page:num
paginate: 10

# Posts settings
permalink: pretty
future: true

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Sass settings
sass:
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - LICENSE
  - node_modules
  - sw-precache-config.js
include:
  - _redirects

# Navigation
nav:
  - label: Writing
    url: /blog/
    theme: t-teal
  - label: Coding
    url: /projects/
    theme: t-green
  - label: Speaking
    url: /speaking/
    theme: t-yellow
  - label: About me
    url: /about/
    theme: t-orange
  - label: Guests posts
    url: /guest/
    theme: t-red
  - label: Search
    url: /search/
    theme: t-pink
