# Site settings
title: Hugo Giraudel
description: >
  I’m Hugo Giraudel, a non-binary web developer based in Berlin, focused on accessibility and inclusivity.
baseurl: ''
url: 'https://hugogiraudel.com'

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Pagination settings
plugins: [jekyll-paginate]
paginate_path: /blog/:num
paginate: 10

# Posts settings
permalink: pretty
future: false
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

# Sass settings
sass:
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - LICENSE
  - node_modules
  - sw-precache-config.js
include:
  - _redirects
environment: production

# Navigation
nav:
  - label: Writing
    url: /blog/
  - label: Coding
    url: /projects/
  - label: Speaking
    url: /speaking/
  - label: About
    url: /about/
  - label: Guests
    url: /guest/
  - label: Search
    url: /search/

# Liquid utilities
empty_list: []
